//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "contact_edit.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>

#include "../models/contact.hpp"

std::string contact_edit::genText(const DrTemplateData& contact_edit_view_data)
{
	drogon::OStringStream contact_edit_tmp_stream;
	std::string layoutName{""};
    using namespace dws::models;
    auto contact=contact_edit_view_data.get<Contact>("contact");
	contact_edit_tmp_stream << "<div name=\"edit-contact\">\n";
	contact_edit_tmp_stream << "    <div class=\"input-group mb-3 input-group-sm\">\n";
	contact_edit_tmp_stream << "     <div class=\"input-group-prepend\">\n";
	contact_edit_tmp_stream << "       <span class=\"input-group-text\">First name</span>\n";
	contact_edit_tmp_stream << "    </div>\n";
	contact_edit_tmp_stream << "    <input class=\"form-control\" name=\"firstname\" id=\"firstname\" type=\"text\" placeholder=\"First name\" value=\"";
contact_edit_tmp_stream<<contact.FirstName;
	contact_edit_tmp_stream << "\">\n";
	contact_edit_tmp_stream << "  </div>\n";
	contact_edit_tmp_stream << "  <div class=\"input-group mb-3 input-group-sm\">\n";
	contact_edit_tmp_stream << "     <div class=\"input-group-prepend\">\n";
	contact_edit_tmp_stream << "       <span class=\"input-group-text\">Last name</span>\n";
	contact_edit_tmp_stream << "    </div>\n";
	contact_edit_tmp_stream << "    <input class=\"form-control\" name=\"lastname\" id=\"lastname\" type=\"text\" placeholder=\"Last name\" value=\"";
contact_edit_tmp_stream<<contact.LastName;
	contact_edit_tmp_stream << "\">\n";
	contact_edit_tmp_stream << "  </div>\n";
	contact_edit_tmp_stream << "  <div class=\"input-group mb-3 input-group-sm\">\n";
	contact_edit_tmp_stream << "     <div class=\"input-group-prepend\">\n";
	contact_edit_tmp_stream << "       <span class=\"input-group-text\">EMail</span>\n";
	contact_edit_tmp_stream << "    </div>\n";
	contact_edit_tmp_stream << "    <input class=\"form-control\" name=\"email\" id=\"email\" type=\"text\" placeholder=\"EMail\" value=\"";
contact_edit_tmp_stream<<contact.EMail;
	contact_edit_tmp_stream << "\">\n";
	contact_edit_tmp_stream << "  </div>\n";
	contact_edit_tmp_stream << "  <div class=\"input-group mb-3 input-group-sm\">\n";
	contact_edit_tmp_stream << "     <div class=\"input-group-prepend\">\n";
	contact_edit_tmp_stream << "       <span class=\"input-group-text\">Phone</span>\n";
	contact_edit_tmp_stream << "    </div>\n";
	contact_edit_tmp_stream << "    <input class=\"form-control\" name=\"phone\" id=\"phone\" type=\"text\" placeholder=\"Phone\" value=\"";
contact_edit_tmp_stream<<contact.Phone;
	contact_edit_tmp_stream << "\">\n";
	contact_edit_tmp_stream << "  </div>\n";
	contact_edit_tmp_stream << "    <button class=\"btn btn-secondary\"\n";
	contact_edit_tmp_stream << "            hx-get=\"/contacts\"\n";
	contact_edit_tmp_stream << "            hx-target=\"#main\"\n";
	contact_edit_tmp_stream << "            hx-swap=\"innerHTML\">Cancel</button>\n";
	contact_edit_tmp_stream << "    <button class=\"btn btn-primary\"\n";
	contact_edit_tmp_stream << "            hx-post=\"/contacts/";
contact_edit_tmp_stream<<contact.ID;
	contact_edit_tmp_stream << "/edit\"\n";
	contact_edit_tmp_stream << "            hx-include=\"input\"\n";
	contact_edit_tmp_stream << "            hx-target=\"#main\"\n";
	contact_edit_tmp_stream << "            hx-swap=\"innerHTML\">Save</button>\n";
	contact_edit_tmp_stream << "</div>\n";
if(layoutName.empty())
{
std::string ret{std::move(contact_edit_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data;
auto str = std::move(contact_edit_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
