//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
using namespace drogon;
class contact_edit:public DrTemplate<contact_edit>
{
public:
	contact_edit(){};
	virtual ~contact_edit(){};
	virtual std::string genText(const DrTemplateData &) override;
};