//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
using namespace drogon;
class contact:public DrTemplate<contact>
{
public:
	contact(){};
	virtual ~contact(){};
	virtual std::string genText(const DrTemplateData &) override;
};