//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
using namespace drogon;
class contacts:public DrTemplate<contacts>
{
public:
	contacts(){};
	virtual ~contacts(){};
	virtual std::string genText(const DrTemplateData &) override;
};