//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
using namespace drogon;
class contact_new:public DrTemplate<contact_new>
{
public:
	contact_new(){};
	virtual ~contact_new(){};
	virtual std::string genText(const DrTemplateData &) override;
};